version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "main"
    reviewers:
      - "choeseonghyeon"
    assignees:
      - "choeseonghyeon"
    commit-message:
      prefix: "chore"
      prefix-development: "chore"
      include: "scope"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      - dependency-name: "@types/*"
        update-types: ["version-update:semver-patch"]
    groups:
      nestjs:
        patterns:
          - "@nestjs/*"
      typescript:
        patterns:
          - "typescript"
          - "@typescript-eslint/*"
      dev-dependencies:
        dependency-type: "development"
        update-types:
          - "minor"
          - "patch"
